
url: https://mayraaleli85.github.io
baseurl: ""

# Site settings
title: Austin Capital Data
email: gunnar@austincapitaldata.com
description: "A place for people to discuss thier creations"

# Team names, titles and social links
people:
- name: Gunnar Kleemann, Ph.D.
  pic: 4
  position: Principal Data Scientist
  bio: https://mayraaleli85.github.io/Gunnar/
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/gunnarkleemann/
    - title: facebook
      url: https://www.facebook.com/austincapitaldata/
    - title: stack-overflow
      url: #

- name: Rob Foster
  pic: 8
  position: Data Scientist/ Curriculum Developer
  bio: https://mayraaleli85.github.io/Rob/ 
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/fosterrj/
    - title: facebook
      url: https://www.facebook.com/austincapitaldata/
    - title: google-plus
      url: #

- name: Joe Mirza
  pic: 9
  position: Data Science Intern
  bio: https://mayraaleli85.github.io/Joe/
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/joemirza/
    - title: facebook
      url: https://www.facebook.com/austincapitaldata/
    - title: stack-overflow
      url: #
  
- name: Tim Chen
  pic: 12
  position: Data Science Intern
  bio: https://mayraaleli85.github.io/Tim/
  social:
    - title: twitter
      url: 
    - title: linkedin
      url: https://www.linkedin.com/in/chentim/
    - title: stack-overflow
      url: #

- name: Skylar Chadwick
  pic: 6
  position: Content Strategist
  bio: https://mayraaleli85.github.io/Skylar/
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/skylarchadwick/
    - title: facebook
      url: https://www.facebook.com/austincapitaldata/
    - title: stack-overflow
      url: #

- name: Mayra Castro
  pic: 7
  position: Project Manager
  bio: https://mayraaleli85.github.io/Mayra/
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mayra-castro-b0a1b2b7/
    - title: facebook
      url: https://www.facebook.com/austincapitaldata/
    - title: stack-overflow
      url: #

alumni:
- name: Kiersten Henderson, Ph.D.
  pic: 11
  position: Alumni, Data Scientist
  social:
    - title: facebook
      url: https://www.facebook.com/austincapitaldata/
    - title: linkedin
      url: https://www.linkedin.com/in/kierstenhenderson/
    - title: stack-overflow
      url: #

- name: Justine Chia, Ph.D.
  pic: 10
  position: Alumni, Data Scientist
  bio: https://mayraaleli85.github.io/dark-poole-bio/
  social:
    - title: facebook
      url: https://www.facebook.com/austincapitaldata/
    - title: linkedin
      url: https://www.linkedin.com/in/justinechia/
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 9701 Dessau Rd #304
  - line: Austin, TX 78754

# Build settings
markdown: kramdown
permalink: pretty
